### PR TITLE
Add graph pass and output to the composer

### PR DESCRIPTION
**Pull request by gparmer**
- Add petgraph support
- Add dot support through petgraph
- Support two different graphing setups (components and components + interfaces)

### Summary of this Pull Request (PR)

Creates the following output for the `sched_ping_pong.toml` system configuration.

[interfaces_graph.dot.pdf](https://github.com/user-attachments/files/16270596/interfaces_graph.dot.pdf)
[component_graph.dot.pdf](https://github.com/user-attachments/files/16270597/component_graph.dot.pdf)

Infrastructure is there to use the graph for more advanced outputs, but also for its graph algorithms (i.e. to compute the transitive closure, and find overlaps between application graphs).

### Intent for your PR

Choose one (Mandatory):

- [ ] This PR is for a code-review and is intended to get feedback, but not to be pulled yet.
- [x] This PR is mature, and ready to be integrated into the repo.

### Reviewers (Mandatory):

@esmakokten @davidbabono 

### Code Quality

As part of this pull request, I've considered the following:

[Style](https://github.com/gparmer/composite/raw/ppos/doc/style_guide/composite_coding_style.pdf):

- [x] Comments adhere to the Style Guide (SG)
- [x] Spacing adhere's to the SG
- [x] Naming adhere's to the SG
- [x] All other aspects of the SG are adhered to, or exceptions are justified in this pull request
- [x] I have run the auto formatter on my code before submitting this PR (see doc/auto_formatter.md for instructions)

[Code Craftsmanship](http://www2.seas.gwu.edu/~gparmer/posts/2016-03-07-code-craftsmanship.html):

- [x] I've made an attempt to remove all redundant code -- Exception is in the creation of the separate outputs. If we add > 2, we should generalize.
- [x] I've considered ways in which my changes might impact existing code, and cleaned it up
- [x] I've formatted the code in an effort to make it easier to read (proper error handling, function use, etc...)
- [x] I've commented appropriately where code is tricky
- [x] I agree that there is no "throw-away" code, and that code in this PR is of high quality

### Testing

I've tested the code using the following test programs (provide list here):

- [x] sched_ping_pong.toml

### CODE REVIEW

**Comment by esmakokten** [comment]
I wanted to give it a try in my environment, I get the following error when I try to compose sched_ping_pong.toml
```
thread 'main' panicked at src/pipe.rs:19:18:
Failed to run command: Os { code: 2, kind: NotFound, message: "No such file or directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Is there any other initial step necessary? I executed previous steps (./cos init x86_64; ./cos build; ./cos compose ...toml test)

**Comment by gparmer** [comment]
Thanks for this! I have no idea what this is. If you have the chance and it is easy for you, can you do:

`RUST_BACKTRACE=1 ./cos compose....`

That passe sthe backtrace as an environmental variable, and I *believe* it passed it on through to the rust program being run. If it doesn't give you a backtrace, let me know. After my PC meeting tomorrow, I'll retry this to see what's happening here. So sorry for this!!!

**Comment by esmakokten** [comment]
Yeah thats the correct way to pass I was looking for this :) Here is the result with `RUST_BACKTRACE=1`
It seems like generating the cos.img and .dot files for the graph (Image of the system_binaries/cos
_build-test folder below) . 

RUST_BACKTRACE=full output [compose_ouput_backtrace_full.txt](https://github.com/user-attachments/files/16351143/compose_ouput_backtrace_full.txt))

```
thread 'main' panicked at src/pipe.rs:19:18:
Failed to run command: Os { code: 2, kind: NotFound, message: "No such file or directory" }
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
   1: core::panicking::panic_fmt
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/result.rs:1652:5
   3: core::result::Result<T,E>::expect
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/result.rs:1034:23
   4: compose::pipe::Pipe::new
             at ./src/composer/src/pipe.rs:15:18
   5: compose::syshelpers::exec_pipeline::{{closure}}
             at ./src/composer/src/syshelpers.rs:10:26
   6: <core::slice::iter::Iter<T> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/slice/iter/macros.rs:232:27
   7: compose::syshelpers::exec_pipeline
             at ./src/composer/src/syshelpers.rs:7:18
   8: <compose::graph::Graph as compose::passes::Transition>::transition
             at ./src/composer/src/graph.rs:224:17
   9: compose::exec
             at ./src/composer/src/main.rs:75:19
  10: compose::main
             at ./src/composer/src/main.rs:86:21
  11: core::ops::function::FnOnce::call_once
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with 
`RUST_BACKTRACE=full` for a verbose backtrace.
```
image

**Comment by esmakokten** [comment]
I find the problem it actually the issue is in my environment :(

image

Installed graphviz and it works now. Should we add it in /composite/tools/init_env.sh ?

**Review by esmakokten — APPROVED** [review]

**Comment by gparmer** [comment]
Yikes, that's my fault! Yes, we should add it to the environment initialization scripts. I should also fix the error reporting to make it clear what the issue is in that case.

**Comment by gparmer** [comment]
Updated the error reporting [here](https://github.com/gwsystems/composite/pull/483/commits/4f9dd111c558bd9b0a2b2b0cc3a57075ced9b4f4)

Now outputs:
```
thread 'main' panicked at src/pipe.rs:19:18:
Failed to run command: "nothinghere": Os { code: 2, kind: NotFound, message: "No such file or directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by gparmer** [comment]
(Note: I replaced the command being executed with "nothinghere" in this example.)

**Comment by gparmer** [comment]
I also updated `main` to update the `init_env.sh` as you suggested, THANKS!

**Review by davidbabono — APPROVED** [review]
I have tested this PR on my local PC. The dependency graphs are generated successfully.

**Pull request merged**
