### PR TITLE
User-level thread dispatch on x86

### PR DESCRIPTION
**Pull request by phanikishoreg**
### Summary of this Pull Request (PR)

This PR adds user-level thread dispatch feature.

@hungry-foolish some pointers for code changes in this PR:
* Look at llbooter (boot_deps.h) for SCB page setup for each component and initial DCB page setup for root-scheduler.
* Look at platform/i386/boot_comp.c for SCB and INIT DCB page setup for the root-component.
* Look into sl.h for user-level dispatch routine (in assembly).
* Look into cos_kernel_api.c for SCB page and component allocation api changes. Also for DCB page allocation api. (This will change soon.)
* Look into cos_kernel_api.c for changes to thread allocation api to pass in the address of DCB entry.
* Look into cos_kernel_api, sl, capmgr for other changes that enable the rest of the system use SCB/DCB/user-level dispatch functionality.

**TODO:**
* SCB and DCB capability abstraction (next thing that I'll be working on!)
* Code optimization in kernel fast-path code section for restoring thread consistency.
* SL optimization to bring down the cycles in "schedule()" like function to about ~30-50cycles. sl_thd_yield() as of now is about 280 cycles with just RR (compared to 670 cycles with just kernel switches and using FPRR).
* more..

**NOTE:** 
* This branch is based on smp-ioapic stuff which is beyond ppos (with IOAPIC stuff) too. 

### Intent for your PR

Choose one (Mandatory):

- [x] This PR is for a code-review and is intended to get feedback, but not to be pulled yet.
- [ ] This PR is mature, and ready to be integrated into the repo.

### Reviewers (Mandatory):
@hungry-foolish @gparmer 

### Code Quality

As part of this pull request, I've considered the following:

[Style](https://github.com/gparmer/composite/raw/ppos/doc/style_guide/composite_coding_style.pdf):

- [x] Comments adhere to the Style Guide (SG)
- [x] Spacing adhere's to the SG
- [x] Naming adhere's to the SG
- [x] All other aspects of the SG are adhered to, or exceptions are justified in this pull request
- [ ] I have run the auto formatter on my code before submitting this PR (see doc/auto_formatter.md for instructions)

[Code Craftsmanship](http://www2.seas.gwu.edu/~gparmer/posts/2016-03-07-code-craftsmanship.html):

- [x] I've made an attempt to remove all redundant code
- [x] I've considered ways in which my changes might impact existing code, and cleaned it up
- [x] I've formatted the code in an effort to make it easier to read (proper error handling, function use, etc...)
- [x] I've commented appropriately where code is tricky
- [ ] I agree that there is no "throw-away" code, and that code in this PR is of high quality

### Testing

I've tested the code using the following test programs (provide list here):

- [x] micro_booter
- [ ] unit_pingpong
- [x] unit_schedtests
- [ ] ...(add others here)

### CODE REVIEW

**Comment by gparmer** [comment]
There are a lot of modified files here.  Which are the main ones that are going to be relevant to @hungry-foolish ?

**Comment by gparmer** [comment]
(love to get all of this into mainline when it is ready, BTW)

**Comment by phanikishoreg** [comment]
I updated the PR description for changes in different files. 
@hungry-foolish 
I think the most relevant ones are page sharing for SCB and DCB in boot_comp.c, boot_deps.h, thread and component allocation api cos_kernel_api.c to accommodate the same and the user-level dispatch logic in sl.h. 

Rest of the changes are to enable this functionality to be used by rest of the system (other user-level components using capmgr for resources.)

**Comment by gparmer** [comment]
I'm going to close this out, and we can re-pull given all that is happening with the loader, cfe, and this.

Sorry for the overhead, but a lot has changed since this was made.

**Pull request closed without merging**
