### PR TITLE
update the exceptions vector number

### PR DESCRIPTION
**Pull request by huachuan**
Non-maskable Interrupt is missing, option one is add it after the IRQ_DEBUG_TRAP; option two is what I did, manually set the vector numbers

### Summary of this Pull Request (PR)

**Add description here.**

### Intent for your PR

Choose one (Mandatory):

- [x] This PR is for a code-review and is intended to get feedback, but not to be pulled yet.
- [ ] This PR is mature, and ready to be integrated into the repo.

### Reviewers (Mandatory):
(Specify @<github.com username(s)> of the reviewers. Ex: @user1, @user2)

### Code Quality

As part of this pull request, I've considered the following:

[Style](https://github.com/gparmer/composite/raw/ppos/doc/style_guide/composite_coding_style.pdf):

- [ ] Comments adhere to the Style Guide (SG)
- [ ] Spacing adhere's to the SG
- [x] Naming adhere's to the SG
- [ ] All other aspects of the SG are adhered to, or exceptions are justified in this pull request
- [ ] I have run the auto formatter on my code before submitting this PR (see doc/auto_formatter.md for instructions)

[Code Craftsmanship](http://www2.seas.gwu.edu/~gparmer/posts/2016-03-07-code-craftsmanship.html):

- [ ] I've made an attempt to remove all redundant code
- [ ] I've considered ways in which my changes might impact existing code, and cleaned it up
- [ ] I've formatted the code in an effort to make it easier to read (proper error handling, function use, etc...)
- [ ] I've commented appropriately where code is tricky
- [ ] I agree that there is no "throw-away" code, and that code in this PR is of high quality

### Testing

I've tested the code using the following test programs (provide list here):

- [ ] micro_booter
- [ ] unit_pingpong
- [ ] unit_schedtests
- [ ] ...(add others here)

### CODE REVIEW

**Comment by gparmer** [comment]
This change obviously takes the system closer to correctness, so it is great. Which is the interrupt vector that you're making not be represented in the enum (presumably offset 2)?

**Comment by huachuan** [comment]
> This change obviously takes the system closer to correctness, so it is great. Which is the interrupt vector that you're making not be represented in the enum (presumably offset 2)?

Vector number 2 Non-maskable Interrupt is not in the enum.

**Comment by gparmer** [comment]
I see. I think that the correct change, then, is

1. to add the NMI handler to the enum (for documentation purposes), and 
2. to prevent this bug in the future by explicitly placing a `= 2`, ` = 3`, etc... after every entry. That way we are explicit, and it is easy to check. 

Would these changes be possible?

Sorry for missing your response!!!

**Comment by huachuan** [comment]
I have added the Non-maskable Interrupt and explicitly placed the exception numbers after every entry.

**Pull request closed without merging**
