### PR TITLE
Multi-core in llbooter, capmgr, sl, cos_kernel_api(locks) and other related

### PR DESCRIPTION
**Pull request by phanikishoreg**
### Summary of this Pull Request (PR)

This PR has all the required (at least the basic facilities for foundation) for cross-cpu and parent-child communication and for any 2 parties to communicate (through channels) and bug-fixes in core interfaces and libraries for multi-core. 

channel: 
* new interface for providing shared memory channels.

capmgr: 
* per-core data structures for threads and per-core initialization
* implement "channel" interface for creating/mapping shared memory with a channel key.
* capmgr_thd_retrieve api to return the thdid of the initthd in the child component to aid in getting the initthd(schedthd) for a lazy child thread lookup.

sched/schedinit:
* bug-fix in schedinit_child interface where thread was being retrieved on a call to sl_thd_lkup, so added sl_thd_try_lkup (in sl) to avoid that.
* Make schedinit_child return the cbuf_t ID to the child after parent creates a shared memory, initializes a ring-buffer in it and returns the ID to the child to map in that shared memory and process events from there.

llbooter:
* per-core data structures and per-core initialization: Scheduling information is tracked for every core for a system with per-core hierarchies
* TODO: run-script and/or configuration (static) for identifying per-core hierarchies.

sl:
* per-core data structures: per-core global data and sl_thd structures
* sl_xcpu: For cross-cpu (cross-core) communication. API for asynchronous thread creation on destination core. Only one API for cross-core thread creation is implemented and the rest return -ENOSUP for now. (TODO: rename to sl_xcore).
* TODO: sl_init to be passed a CPU bitmap for initializing for only those cores and for creating asnds for communication with only those cores. Right now, its hardcoded in sl_init to initialize for NUM_CPU number of cores.
* sl_child: For parent-child communication. To enable child threads to make invocations into the parent and be blocked. This lets the parent notify it's child scheduler of its thread blocking.

cos_kernel_api:
* bug-fixes for multi-core parallelism. 
* locks for making cap/mem bumps and vas expands atomic. This is not great because it is not wait-free. This is the reason for not marking "This PR is mature" checkbox.

ck submodule:
* added ck submodule in components/lib/ck and using SPSC and MPSC ck_ring in sl_child and sl_xcpu respectively.

### Intent for your PR

Choose one (Mandatory):

- [x] This PR is for a code-review and is intended to get feedback, but not to be pulled yet.
- [ ] This PR is mature, and ready to be integrated into the repo.

### Reviewers (Mandatory):
@gparmer @ryuxin @yzcode 

### Code Quality

As part of this pull request, I've considered the following:

[Style](https://github.com/gparmer/composite/raw/ppos/doc/style_guide/composite_coding_style.pdf):

- [x] Comments adhere to the Style Guide (SG)
- [x] Spacing adhere's to the SG
- [x] Naming adhere's to the SG
- [x] All other aspects of the SG are adhered to, or exceptions are justified in this pull request
- [ ] I have run the auto formatter on my code before submitting this PR (see doc/auto_formatter.md for instructions)

[Code Craftsmanship](http://www2.seas.gwu.edu/~gparmer/posts/2016-03-07-code-craftsmanship.html):

- [x] I've made an attempt to remove all redundant code
- [x] I've considered ways in which my changes might impact existing code, and cleaned it up
- [x] I've formatted the code in an effort to make it easier to read (proper error handling, function use, etc...)
- [x] I've commented appropriately where code is tricky
- [x] I agree that there is no "throw-away" code, and that code in this PR is of high quality

### Testing

I've tested the code using the following test programs (provide list here):

- microbooter, unit_capmgr, unit_schedcomp, unit_hiersched for 1, 2 and 4 cores. (some on HW, some on Qemu)
- unit_fprr - modified to support multi-core and added unit-test for cross-core thread creation.
- tested parent-child communication in a hacky way to confirm that the child is able to dequeue the exact requests from parent.

### CODE REVIEW

**Comment by gparmer** [comment]
I really hope that you addressed all of the issues.  I looked through the commits after feedback, and there isn't much there...but I don't remember what the feedback was at this point, so that might be OK.  I'm taking you on your word ;-)

**Comment by phanikishoreg** [comment]
Never mind. I just realized this is to "smp" branch which is not mainline ppos. 
My mistake to not have noticed that it was not a PR to mainline ppos. 

We can do the review process when I PR it to the mainline.

**Comment by gparmer** [comment]
I misunderstood.  I thought you said before that this was ready and post-changes.  I thought I did give feedback.  Did I only give feedback on a subset of the PR?

**Comment by phanikishoreg** [comment]
I have said that for the other "ready to merge" PRs and but not this one I think. :-)
Yeah, you provided feedback for a commit that I directly referenced on slack some time back.

**Pull request merged**
