### PR TITLE
Base0x10 patch 1

### PR DESCRIPTION
**Pull request by base0x10**
### Summary of this Pull Request (PR)

This PR only updates some outdated documentation, and
fixes the vagrantscript

### Intent for your PR

Choose one (Mandatory):

- [ ] This PR is for a code-review and is intended to get feedback, but not to be pulled yet.
- [ X] This PR is mature, and ready to be integrated into the repo.

### Reviewers (Mandatory):
(Specify @<github.com username(s)> of the reviewers. Ex: @user1, @user2)
@gparmer 
@Others 

### Code Quality

There is no new code in this PR, only updates to docs and vagrantfile options

As part of this pull request, I've considered the following:

[Style](https://github.com/gparmer/composite/raw/ppos/doc/style_guide/composite_coding_style.pdf):

- [ ] Comments adhere to the Style Guide (SG)
- [ ] Spacing adhere's to the SG
- [ ] Naming adhere's to the SG
- [ ] All other aspects of the SG are adhered to, or exceptions are justified in this pull request
- [ ] I have run the auto formatter on my code before submitting this PR (see doc/auto_formatter.md for instructions)

[Code Craftsmanship](http://www2.seas.gwu.edu/~gparmer/posts/2016-03-07-code-craftsmanship.html):

- [ X] I've made an attempt to remove all redundant code
- [ ]X I've considered ways in which my changes might impact existing code, and cleaned it up
- [ X] I've formatted the code in an effort to make it easier to read (proper error handling, function use, etc...)
- [ X] I've commented appropriately where code is tricky
- [ X] I agree that there is no "throw-away" code, and that code in this PR is of high quality

### Testing

I've tested the code using the following test programs (provide list here):

Tested that changes to vagrantfile work on a new install.  Will require rebuilding
a vm to pass ioapic 

- [ ] micro_booter
- [ ] unit_pingpong
- [ ] unit_schedtests
- [ ] ...(add others here)

### CODE REVIEW

**Comment by gparmer** [comment]
I dropped the ball on this, and you've since moved to docker. I presume that closing this is the correct course. I can reopen, if you want to work from here with the docker stuff.

**Comment by Others** [comment]
@gparmer would it be possible to reopen and merge this? I use vagrant and have to manually install g++ every time. Also it’s good to document the changed “default” runscript

**Comment by gparmer** [comment]
@Others Absolutely. I fixed the remaining merge conflict. Can you attest to this being good to go? I don't have the setup to test this. If you're good with it, it can be merged.

**Comment by gparmer** [comment]
@Others @base0x10 Ping. Love to merge, and don't have the setup to test that it works. Mind attesting it works?

**Comment by base0x10** [comment]
@gparmer Tested and works.  kernel_tests.sh and unit_schedtests.sh both run successfully without reporting any issues.  I didn't compare performance against baremetal or other virtualization platforms.  Issue described below isn't blocking and doesn't seem to have to do with vagrant, but rather with rust nightly.  I don't think it should block merging this PR, but up to you.  

@Others there is currently an issue with rust related to [this issue](https://github.com/rust-lang/rust/issues/68318).  Does not prevent building or running the system without rust.  I have attached the output: [issue.txt](https://github.com/gwsystems/composite/files/4482739/issue.txt)

**Comment by gparmer** [comment]
I swear I pulled this a week ago? I need to go back through the records ;-(

**Comment by gparmer** [comment]
Thanks for this update!!!

**Comment by Others** [comment]
@base0x10 regarding the rust issue, did you use nightly?

**Pull request merged**
